src/foundation/urls.py
from django.contrib import admin
from django.conf import settings
from django.urls import path, include
from django.contrib.auth import views as auth_views

from . import views

app_name = 'foundation'

urlpatterns = [
    path('', views.index, name="index"),
    
    # Client views
    path('client/create', views.create_client, name="create_client"),
    path('client/<int:pk>/update', views.update_client, name="update_client"),
    path('client/<int:pk>/delete', views.delete_client, name="delete_client"),
    path('client/<int:pk>/projects', views.client_projects, name="client_projects"),
    path('clients', views.ClientListView.as_view(), name="clients"),
    
    # Project views
    path('project/create', views.create_project, name="create_project"),
    path('project/<int:pk>/update', views.update_project, name="update_project"),
    path('project/<int:pk>/delete', views.delete_project, name="delete_project"),
    path('projects', views.ProjectListView.as_view(), name="projects"),
    
    # Payments views
    path('payments', views.PaymentListView.as_view(), name="payments"),
    
    # Auth views
    path("login/", auth_views.LoginView.as_view(template_name="login.html", redirect_authenticated_user=True), name="login"),
    path("logout/", auth_views.LogoutView.as_view(), name="logout"),
    
    # Admin views
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar
    
    urlpatterns.append(path("__debug__/", include(debug_toolbar.urls)))

src/foundation/models.py
from django.db import models
from django.contrib.auth.models import User

class Audit(models.Model):
    deleted = models.BooleanField(default=False, db_index=True)
    createdAt = models.DateTimeField(auto_now_add=True, db_column="created_at")
    createdBy = models.ForeignKey(User, null=True, db_column="created_by", on_delete=models.SET_NULL) 

    class Meta:
        abstract = True
        ordering = ['-createdAt']

class StateAudit(Audit):
    active = models.BooleanField(default=True, db_index=True)
    
    def delete(self, **kwargs):
        self.active = False
        self.deleted = True
        self.save(**kwargs)
        
        super().save(**kwargs)

    class Meta:
        abstract = True
        indexes = [ models.Index(fields=["active"]) ]

class Client(StateAudit):
    name = models.CharField(max_length=100, unique=True)
    email = models.EmailField(unique=True)

    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "client"
        
class Project(StateAudit):
    name = models.CharField(max_length=100, unique=True)
    amount = models.FloatField()
    client = models.ForeignKey(Client, on_delete=models.CASCADE, related_name='projects')
    
    def delete(self, **kwargs):
        # "Delete" project payments
        PayDay.objects.filter(project=self, deleted=False, active=True).update(deleted=True, active=False)
        Payment.objects.filter(project=self, payed=False, active=True).update(active=False)
        
        super().delete(**kwargs)
    
    def __str__(self):
        return self.name
    
    class Meta:
        db_table = "project"

class PayDay(models.Model):
    day = models.SmallIntegerField()
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING, related_name='pay_days')
    active = models.BooleanField(default=True, db_index=True)
    deleted = models.BooleanField(default=False, db_index=True)
    
    class Meta:
        db_table = "pay_day"
        
class Payment(models.Model):
    amount = models.FloatField()
    due_date = models.DateField()
    project = models.ForeignKey(Project, on_delete=models.DO_NOTHING, related_name='payments')
    payed = models.BooleanField(default=False, db_index=True)
    payed_at = models.DateTimeField(null=True)
    active = models.BooleanField(default=False, db_index=True)
    
    class Meta:
        db_table = "payment"

src/foundation/forms/client.py
from django import forms
from ..models import Client

def get_active_clients():
    return Client.objects.filter(active__exact=True, deleted__exact=False)

class CreateClientForm(forms.Form):
    name = forms.CharField(max_length=100, required=True, strip=True)
    email = forms.EmailField(required=True)
    
class UpdateClientForm(CreateClientForm):
    active = forms.BooleanField(required=True)

src/foundation/forms/project.py
from django import forms
from ..models import Client, Project

default_field_classes = 'bg-gray-50 border border-gray-600 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5 dark:bg-gray-700 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500 mb-2'

class CreateProjectForm(forms.ModelForm):    
    payDays = forms.MultipleChoiceField(
        label='Pay day(s)',
        choices=[(i, i) for i in range(1, 31)],
        widget=forms.SelectMultiple(attrs={'class': default_field_classes})
    )
    
    class Meta:
        model = Project
        fields = ["name", "amount", "client", 'payDays']
        
    def __init__(self, *args, **kwargs):
        self.user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)
        
        for field in self.fields.values():
            field.widget.attrs.update({ "class": default_field_classes })
            
        if self.user:
            self.fields['client'].queryset = Client.objects.filter(active__exact=True, 
                                                                   deleted__exact=False, 
                                                                   createdBy=self.user)

class UpdateProjectForm(CreateProjectForm):
    active = forms.BooleanField(required=True)

src/foundation/views.py
from django.http import HttpRequest, HttpResponseRedirect, HttpResponseForbidden
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.views.decorators.http import require_http_methods
from background_task.models import Task

from foundation.models import Client, PayDay, Payment, Project
from foundation.forms.project import CreateProjectForm, UpdateProjectForm
from foundation.forms.client import CreateClientForm, UpdateClientForm
from foundation.auth.decorators import user_owns_resource
from foundation.task import notify_due_payments, schedule_payments
from foundation.utils import get_next_month_date

@login_required
def index(request: HttpRequest):
    
    # Schedule tasks
    notify_due_payments()
    schedule_payments(repeat=Task.DAILY)
    
    context = {
        'clients_count': Client.objects.filter(deleted=False, createdBy = request.user).count(),
        'projects_count': Project.objects.filter(deleted=False, createdBy = request.user).count()
    }
    return render(request, 'index.html', context)

@login_required
def create_client(request: HttpRequest):
    if request.method == "POST":
        form = CreateClientForm(request.POST)
        
        if not form.is_valid():
            return render(request, "client/create.html", { "errors": form.errors })
        
        Client(createdBy=request.user, **form.cleaned_data).save()
        messages.success(request, "Client created")
        
        return HttpResponseRedirect(reverse("clients"))
    
    else:
        return render(request, "client/create.html", { "form": CreateClientForm() })

@require_http_methods(["POST"])
@user_owns_resource(Client)
def update_client(request: HttpRequest, pk: int):
    client = get_object_or_404(Client, pk=pk)
    
    if not client.createdBy == request.user:
        HttpResponseForbidden()
        
    form = UpdateClientForm(request.POST)
    
    if not form.is_valid():
        messages.error(request, "The submitted form had errors.")
        return HttpResponseRedirect(reverse("clients"))
        
    client.name = form.cleaned_data['name'] 
    client.email = form.cleaned_data['email']
    client.active = request.POST['active'] == "1"
    client.save()
    
    messages.success(request, "Client details updated.")
    
    return HttpResponseRedirect(reverse("clients"))

@require_http_methods(["POST"])
@user_owns_resource(Client)
def delete_client(request: HttpRequest, pk: int):
    client = get_object_or_404(Client, pk=pk)
    client.delete()
    
    messages.success(request, "Client deleted successfully.")
    
    return HttpResponseRedirect(reverse("clients"))

class ClientListView(LoginRequiredMixin, ListView):
    model = Client
    template_name="client/list.html"
    
    def get_queryset(self):
        return (Client.objects
                     .filter(deleted=False, createdBy = self.request.user)
                     .values('id', 'name', 'email', 'createdAt', 'active'))

@login_required
def client_projects(request, pk):
    client = get_object_or_404(Client, pk=pk)
    
    context = {
        "client": client,
        "clients": Client.objects.filter(deleted=False).values('id', 'name'),
        "projects": (Project.objects.prefetch_related("client", "pay_days")
                                    .filter(deleted=False, client_id=client.id))
    }
    
    return render(request, "client/projects.html", context)
        
## Projects views
@login_required
def create_project(request: HttpRequest):
    if request.method == "POST":
        form = CreateProjectForm(request.POST)
        
        if not form.is_valid():
            return render(request, "project/create.html", { "form": form, "errors": form.errors })
        
        project = Project.objects.create(
            name = form.cleaned_data['name'],
            amount = form.cleaned_data['amount'],
            client = form.cleaned_data['client'],
            createdBy = request.user,
        )
        
        for day in form.cleaned_data['payDays']:
            PayDay(day=day, project=project).save()
            Payment(amount=project.amount, project=project, due_date=get_next_month_date(int(day))).save()
        
        messages.success(request, "Project created")
        
        return HttpResponseRedirect(request.path_info)
    
    else:
        client_id = request.GET.get('client')
        
        if client_id:
            get_object_or_404(Client, pk=client_id)
            
        form = CreateProjectForm(initial={ 'client': client_id }, user=request.user)
        
        return render(request, "project/create.html", { "form": form })

@require_http_methods(["POST"])
@user_owns_resource(Project)
def delete_project(request: HttpRequest, pk: int):
    project = get_object_or_404(Project, pk=pk)
    project.delete()
    
    messages.success(request, "Project deleted successfully.")
    
    return HttpResponseRedirect(reverse("projects"))
 
class ProjectListView(LoginRequiredMixin, ListView):
    model = Project
    template_name="project/list.html"       
    
    def get_queryset(self):
        return (Project.objects.prefetch_related("client", "pay_days")
                               .filter(deleted=False, createdBy = self.request.user))
                               
    def get_context_data(self, **kwargs):
        context = super(ProjectListView, self).get_context_data(**kwargs)
        context['clients'] = (Client.objects.filter(active=True, deleted=False, createdBy=self.request.user)
                                            .values('id', 'name'))
        
        return context

@require_http_methods(["POST"])
@user_owns_resource(Project)
def update_project(request: HttpRequest, pk: int):
    project = get_object_or_404(Project, pk=pk)
    form = UpdateProjectForm(request.POST, instance=project)
    
    if not form.is_valid():
        messages.error(request, "The submitted form had errors.")
        return HttpResponseRedirect(reverse("projects"))
        
    project.name = form.cleaned_data['name'] 
    project.amount = form.cleaned_data['amount']
    project.client = form.cleaned_data['client']
    project.active = request.POST['active'] == "1"
    project.save()
    
    messages.success(request, "Project details updated.")
    
    return HttpResponseRedirect(reverse("projects"))

## Payments views
class PaymentListView(LoginRequiredMixin, ListView):
    model = Payment
    template_name="payment/list.html"       
    
    def get_queryset(self):
        return (Payment.objects.prefetch_related("project__client")
                               .filter(project__createdBy = self.request.user)
                               .order_by('due_date'))

src/foundation/templates/payment/list.html
{% extends "layout.html" %}

{% block title %}{{ block.super}} :: Payments{% endblock %}

{% block main %}

<div class="py-6 px-8 mt-4 text-gray-900 dark:text-white">
    <h1 class="text-2xl font-bold">Payments
    </h1>

    {% include 'payment/payments_table.html' with payments=payment_list %}
</div>
{% endblock %}

src/foundation/templates/payment/payments_table.html
{% load datetime_formatter %}

<div class="relative overflow-hidden pb-16 sm:rounded-lg">
    <div
        class="flex items-center justify-between flex-column md:flex-row flex-wrap space-y-4 md:space-y-0 py-4 bg-white dark:bg-gray-900">
        <div class="mb-0">
            <button id="dropdownActionButton"
                data-dropdown-toggle="dropdownAction"
                class="inline-flex items-center text-gray-500 bg-white border border-gray-600 focus:outline-none hover:bg-gray-100 focus:ring-4 focus:ring-gray-100 font-medium rounded-lg text-sm px-3 py-1.5 dark:bg-gray-800 dark:text-gray-400 dark:border-gray-600 dark:hover:bg-gray-700 dark:hover:border-gray-600 dark:focus:ring-gray-700"
                type="button">
                <span class="sr-only">Action button</span>
                Action
                <svg class="w-2.5 h-2.5 ms-2.5" aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg" fill="none"
                    viewBox="0 0 10 6">
                    <path stroke="currentColor" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="2"
                        d="m1 1 4 4 4-4" />
                </svg>
            </button>
            <div id="dropdownAction"
                class="z-10 hidden bg-white divide-y divide-gray-100 rounded-lg shadow-sm w-44 dark:bg-gray-700 dark:divide-gray-600">
                <ul class="py-1 text-sm text-gray-700 dark:text-gray-200"
                    aria-labelledby="dropdownActionButton">
                    <li>
                        <a href="#"
                            class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Reward</a>
                    </li>
                    <li>
                        <a href="#"
                            class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Promote</a>
                    </li>
                    <li>
                        <a href="#"
                            class="block px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600 dark:hover:text-white">Activate
                            account</a>
                    </li>
                </ul>
                <div class="py-1">
                    <a href="#"
                        class="block px-4 py-2 text-sm text-gray-700 hover:bg-gray-100 dark:hover:bg-gray-600 dark:text-gray-200 dark:hover:text-white">Delete
                        User</a>
                </div>
            </div>
        </div>
        <label for="table-search" class="sr-only">Search</label>
        <div class="relative">
            <div
                class="absolute inset-y-0 rtl:inset-r-0 start-0 flex items-center ps-3 pointer-events-none">
                <svg class="w-4 h-4 text-gray-500 dark:text-gray-400"
                    aria-hidden="true" xmlns="http://www.w3.org/2000/svg"
                    fill="none" viewBox="0 0 20 20">
                    <path stroke="currentColor" stroke-linecap="round"
                        stroke-linejoin="round" stroke-width="2"
                        d="m19 19-4-4m0-7A7 7 0 1 1 1 8a7 7 0 0 1 14 0Z" />
                </svg>
            </div>
            <input type="text" id="table-search-users"
                class="block pt-2 ps-10 text-sm text-gray-900 border border-gray-600 rounded-lg w-80 bg-gray-50 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500"
                placeholder="Search for payments">
        </div>
    </div>
    <table
        class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400 sm:rounded-lg">
        <thead
            class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
            <tr>
                <th scope="col" class="px-4 py-3">
                    Amount
                </th>
                <th scope="col" class="px-4 py-3">
                    Client
                </th>
                <th scope="col" class="px-4 py-3">
                    Project
                </th>
                <th scope="col" class="px-4 py-3">
                    Due date
                </th>
                <th scope="col" class="px-4 py-3">
                    Payed at
                </th>
                <th scope="col" class="px-4 py-3">
                </th>
            </tr>
        </thead>
        <tbody>
            {% for payment in payments %}
            <tr
                class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 border-gray-200 hover:bg-gray-50 dark:hover:bg-gray-600">
                <td class="px-4 py-2">
                    {{ payment.amount|floatformat:"2g" }}
                </td>
                <td class="px-4 py-2 text-base font-semibold dark:text-white">
                    {{ payment.project.client.name }}
                </td>
                <td class="px-4 py-2 text-base font-semibold dark:text-white">
                    {{ payment.project.name }}
                </td>
                <td class="px-4 py-2">
                    {{ payment.due_date|date:"m/d/Y"  }}
                </td>
                <td class="px-4 py-2">
                    <div class="flex items-center">
                        {% if payment.payed_at %}
                        {{ payment.payed_at|format_datetime }}
                        {% else %}
                        <span
                            class='py-1 px-2 rounded-full bg-red-500 me-2 text-white text-xs font-semibold'>N/A</span>
                        {% endif %}
                    </div>
                </td>
                <td class="px-4 py-2">

                    <!-- ACTIONS DROPDOWN START -->
                    <button id="dropdownDefaultButton-{{ payment.id }}"
                        data-dropdown-toggle="dropdown-{{ payment.id }}"
                        class="inline-flex items-center p-0.5 text-sm font-medium text-center text-gray-500 hover:text-gray-800 rounded-lg focus:outline-none dark:text-gray-400 dark:hover:text-gray-100"
                        type="button">
                        <svg class="w-5 h-5" aria-hidden="true"
                            fill="currentColor" viewBox="0 0 20 20"
                            xmlns="http://www.w3.org/2000/svg">
                            <path
                                d="M6 10a2 2 0 11-4 0 2 2 0 014 0zM12 10a2 2 0 11-4 0 2 2 0 014 0zM16 12a2 2 0 100-4 2 2 0 000 4z">
                            </path>
                        </svg>
                    </button>

                    <div id="dropdown-{{ payment.id }}"
                        class="z-10 w-32 bg-white rounded text-gray-700 divide-y hidden divide-gray-100 shadow dark:bg-gray-700 dark:divide-gray-600">
                        <ul class="py-0 text-sm dark:text-gray-200"
                            aria-labelledby="dropdownDefaultButton-{{ payment.id }}">
                            <li>
                                <button
                                    data-modal-target="editClientModal-{{ payment.id }}"
                                    data-modal-show="editClientModal-{{ payment.id }}"
                                    class="block w-full text-left px-4 py-2 hover:bg-gray-100 dark:hover:bg-gray-600">Mark
                                    as payed</a>
                            </li>
                        </ul>
                    </div>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="100%" aria-colspan="100%" class="text-center py-4">
                    No payments registered
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>